### ISSUE TITLE
Auxread misses some class components due to an error with multi_stack.

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#101]
The aux_save for tree_class makes files _-G-layer-1-perms for the group files. When auxread tries to read these same files in it looks for files that look like _-G_-layer-1-perms if multi_stack and rstack aren't present:
```
    if (present(multi_stack) .and. present(rstack)) then
       lfolder = folder
    else
       lfolder = folder//'_'
    end if
```
As a result auxread doesn't capture any of the group data and any tests or programs that use group data fail. I'm not sure if this is a bug or not but it's been giving me trouble.

**Comment by rosenbrockc** [comment]
It's a bug. The `auxsave` and `auxread` should just work out of the box. We'll take a look at it on Friday.

**Comment by rosenbrockc** [comment]
Refactored `fpy_auxiliary` to deal with arrays where the array has been initialized, but its contents don't necessarily produce files for each element. In that case, the array was not being restored to the correct size and state. New files called `.fpy.blank` are created for array elements who are allocated, but don't produce files with values. Then, when `auxread` is called, the same array structure with allocated, but empty, variables is restored.
