### ISSUE TITLE
1D array maximum size of 37500.

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#103]
There seems to be an internal limit on the size range of an array being read in from file within fortpy. The limit appears to be 37500 entries. When an array is larger than that the array is truncated which results in the following types of errors when the model input is read in and manipulated:

```
Fortran runtime error: Index '40747' of dimension 1 of array 'self%base' above upper bound of 37500
Fortran runtime error: Index '38557' of dimension 1 of array 'self%base' above upper bound of 37500
```

**Comment by rosenbrockc** [comment]
Fixed in Revision 1.7.6.
