### ISSUE TITLE
Add a "return" to the single line in the SUCCESS file

### ISSUE THREAD

**Issue by glwhart** [rosenbrockc/fortpy#124]
This would make it easier when parsing or listing these files.

This is a 5 minute fix.

Ditto for the output "The result comparison failed. Check the unit test console output." It would be nice to have a carriage return at the end of the line...

Ditto for the driver programs that fortpy creates. The last line of each does not have a carriage return at the end. When one `cat`s the files, etc., the output is a bit messy.

**Comment by rosenbrockc** [comment]
Fixed in current state of `debug` branch.
