### ISSUE TITLE
Warn when `FORTPY_CONFIG` is not set or when fortpy.config.xml is present (whenever `runtest.py` is called)

### ISSUE THREAD

**Issue by glwhart** [rosenbrockc/fortpy#125]
Warn when `FORTPY_CONFIG` is not set or when `fortpy.config.xml` is not present. (This should be checked everytime `runtest.py` is called)

Spent a long time debugging trying to figure out why dependencies were not being found, when new user simply didn't have these two things. This has bitten multiple times because we keep forgetting that you can't just `pip install` and be off to the races...

**Comment by rosenbrockc** [comment]
Fixed on current `debug` branch.
