### ISSUE TITLE
Failure to allocate `perm` in routine `find_permutation_of_group` before calling 

### ISSUE THREAD

**Issue by glwhart** [rosenbrockc/fortpy#128]
The input to the routine `find_permutation_of_group` includes to INTENT(IN) arguments, `g` and `gp`, and one INTENT(OUT) argument, `perm`. The latter is causing a segfault during the unit tests because fortpy does not allocate it before passing it into the routine (which is how it is used in the actual code, allocated at the beginning of  `get_rotation_perms_lists`, the only place it is ever called from).

This is the relevant part of the `derivative_structure_generator.xml` file, around line 225:
```
 <decorates name="derivative_structure_generator.find_permutation_of_group">
    <group name="stuct_enum_tests8" purpose="fortpy broken; issue #128" staging="../unittests/">
```

**Comment by glwhart** [comment]
Not sure if these tests ever worked, maybe they did. I've been turning on tests that are in the xml file and trying to debug them.

**Comment by glwhart** [comment]
There is a similar problem (SEGFAULT) in the tests `group name="stuct_enum_tests12` in `derivative_structure_generator.xml` around line 329. These SNF tests fail with a SEGFAULT and I'm guessing they also have a similar problem---unallocated object passed into the routine that is INTENT(OUT) and uninitialized on its way in (but even if it is uninitialized it still needs to be allocated). I can't check this explicitly because I ran into another problem: I can't execute the executables. When I try, I get an error: 
```
GLWH:get_SNF_A.1 hart$ ../../get_SNF_fixing_op.x 
dyld: Library not loaded: fpy_aux.so
  Referenced from: /Users/hart/codes/staging/derivative_structure_generator.get_SNF.g/tests/get_SNF_A.1/../../get_SNF_fixing_op.x
  Reason: image not found
Abort trap: 6
```
It would be great if you could look at this too. It's a bit perplexing since it doesn't occur when fortpy runs the executable but it does happen when I do it manually on the commandline. BTW, `fpy_aux.so` is definitely there...

**Comment by rosenbrockc** [comment]
The first test `find_permutation_of_group` failed because the variable `perm` hadn't been allocated yet. In the full version of the program, the variable gets allocated to the determinant of the HNF before `find_permutation_of_group` is called.

To fix the unit test, I added:

```xml
<global name="perm" type="integer"  modifiers="allocatable" dimensions=":" />
```

to the test definition, and then set the allocation size in the assignments list:

```xml
<assignment name="g" value="gfile" allocate="true">
  <value identifier="gfile" file="find_permutation_of_group_g.in.{}" 
  folder="../tests/derivative_structure_generator" rename="g.in"/>
</assignment>
<assignment name="gp" value="gpfile" allocate="true">
  <value identifier="gpfile" file="find_permutation_of_group_gp.in.{}"
	folder="../tests/derivative_structure_generator" rename="gp.in"/>
</assignment>
<assignment name="perm" allocate="size(gp,2)" />
```

Since the allocation relies on the variable `gp`, I put it *after* `gp` has its value read from file.

Hopefully this makes sense; let me know if you need clarification.

**Comment by rosenbrockc** [comment]
For the other unit test, after the changes in #127 I now get:

```
Running 1:   0%|          | 0/38 [00:00<?, ?it/s] Fortpy F90 verbosity set to           1 .
 Found            1  lines and            1  values in 'fpy_case'.
 Target file 'HNF.in' does not exist.
ERROR: 
  
  Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
 ```

which shows that segfault is due to a missing unit test file.

Also, when you run interactively, do `DYLD_LIBRARY_PATH=../../ ../../get_SNF_A.x 1` so that the dynamic linking works.
