### ISSUE TITLE
Complex Functions

### ISSUE THREAD

**Issue by rosenbrockc** [rosenbrockc/fortpy#37]
For function output under target name `[default]`, we need to have the `[default]` variable able to be declared as `<global>` and have its value changed using `<assignment>` so that complicated functions can be tuned by the user.

The reason we need to introduce maximum flexibility is that a function may declare its output type using a function of the input parameters; or if the functions output is allocatable, then we need the user to specify the output type in advance so that compilation succeeds.

The fix for this will involve switching out the hard-coded `function_fpy` variable declaration in `elements.py` for a conditional statement that checks the test specification's list of globals first for a `[default]` variable; if it exists, then do nothing. The existing code for initializing and assigning values to the variables will suffice, we just need to change the name that gets output from `[default]` to the fortpy hard-coded value.

**Comment by rosenbrockc** [comment]
This is supported in Revision 1.6.1 by specifying tags like:

```xml
      <global name="[default]" type="integer" modifiers="allocatable" dimension=":" />
      <assignment name="[default]" constant="0" allocate="size(N)" />
```

The `[default`] name refers to the variable that will store the output of the function; it can have `<assignment>` tags reference it to allocate or change its value etc. just like any variable can, the treatment is equivalent.

**Comment by wsmorgan** [comment]
I've found an issue in this new option. It now will set the variable to 0 but doesn't allocate it first. Here is the xml I used:
```
  <decorates name="combinatorics.factorial_int_rank1">
    <group name="binomial_tests" purpose="testing" staging="../unittests/">
      <test identifier="factorial_int_rank1" 
	    description="Testing of the array of integers factorial." timed="true" >
  	<output identifier="factorial_int_arry.out" folder="../tests/combinatorics" 
		file="factorial_int_arry.out" template="integer.xml" />
  	<target name="[default]" compareto="factorial_int_arry.out" 
		varfile="factorial_int_arry.out" when="each" />
      </test>
      <global name="[default]" type="integer" modifiers="allocatable" dimension=":" />
      <assignment name="[default]" constant="0" allocate="size(N)" />
      <assignment name="N" value="mfile2" allocat="true">
  	<value identifier="mfile2" folder="../tests/combinatorics"
  	       file="factorial_array.in"/>
      </assignment>     
    </group>
  </decorates>
```
and here is the driver it produced:
```
PROGRAM UNITTEST_factorial_int_rank1
  use combinatorics
  use fortpy
  implicit none

  integer, allocatable :: factorial_int_rank1_fpy
  integer, allocatable :: N(:)

  real(fdp) :: fpy_start, fpy_end, fpy_elapsed = 0

  factorial_int_rank1_fpy = 0
  call fpy_read('factorial_array.in', '#', N)

  call cpu_time(fpy_start)
  factorial_int_rank1_fpy = factorial_int_rank1(N)
  call cpu_time(fpy_end)
  fpy_elapsed = fpy_elapsed + fpy_end - fpy_start
  call pysave(factorial_int_rank1_fpy, 'factorial_int_arry.out')

  call pysave(fpy_elapsed, 'fpytiming.out')
END PROGRAM UNITTEST_factorial_int_rank1
```

**Comment by rosenbrockc** [comment]
The problem is on this line:

```xml
<global name="[default]" type="integer" modifiers="allocatable" dimension=":" />
```

The attribute _dimension_ should be _dimension**s**_. Then everything compiles and runs correctly.

**Comment by wsmorgan** [comment]
Ah I see. Thanks Conrad.

Wiley Morgan
http://hagrid.byu.edu/Wiley#Bio

On Thu, Jun 25, 2015 at 4:22 PM, Conrad Rosenbrock <notifications@github.com
