### ISSUE TITLE
parser fails to assign type to logical funtions

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#43]
code:
  function is_equiv_lattice(lat1,lat2,eps)
    real(dp), intent(in) :: lat1(3,3), lat2(3,3), eps
    logical is_equiv_lattice, err
    real(dp)  :: lat1inv(3,3), S(3,3)
    integer i
    is_equiv_lattice = .false.
    call matrix_inverse(lat1,lat1inv,err)
    if (err) stop "Problem with input vectors in function 'is_equiv_lattice'"
    S = matmul(lat1inv,lat2)
    if (equal(abs(determinant(S)),1._dp,eps) .and. &
         equal(S,nint(S),eps)) is_equiv_lattice = .true.
  endfunction is_equiv_lattice

fortpy compile log:

is_equiv_lattice.f90:10.2:

  None :: is_equiv_lattice_fpy

**Comment by rosenbrockc** [comment]
This issue is caused by the lack of `::` after the `logical` keyword defining the output type of the function. If we decide that the parser ought to handle the old style of doing it without the `::`, we could work at it. But it is a lot simpler to just require it. Let me know what you think.

**Comment by wsmorgan** [comment]
Making the :: a requirement isn't a big deal, I'll just need to update our older code a bit.
