### ISSUE TITLE
More Helpful XML ParseError Messages

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#45]
For `docstring.py` line #267 add a more helpful error message that shows which token is causing the `ParseError`. Especially useful if the user doesn't know which XML characters are special.

**Comment by rosenbrockc** [comment]
Fixed in Revision 1.5.7; an excerpt of the offending XML will be displayed instead of just printing the whole XML block. Also, for long lines of XML, any characters after the mistake are truncated so that the output looks a bit cleaner.
