### ISSUE TITLE
Allocation of output arrays fails when dependent on input array size

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#47]
If the code is testing a function that a returns an array that is the same size as the input array, i.e.: ```FUNCTION factorial_int_rank1(N) ```
```integer :: N(:),i,factorial_int_rank1(size(N)),j```

Then fortpy tries to allocate the output array before reading the input:
```integer, allocatable :: N(:)```
```integer :: factorial_int_rank1_fpy(size(N))```
```real(fdp) :: fpy_start, fpy_end, fpy_elapsed = 0```
```call fpy_read('factorial_array.in', '#', N)```

**Comment by rosenbrockc** [comment]
This is related to issue #37 and the inability of the user to specify how the output variable should be handled. I will make sure that the fix to that issue fixes this too.

**Comment by rosenbrockc** [comment]
See the comment that closes issue #37; it addresses this function's problem directly.
