### ISSUE TITLE
Function outputting a variable other than it's name fails. 

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#48]
The issue has come up in rational_mathematics.f90, the gcd functions all return a divisor and not the normal format:
```  function gcd_2ints(x1, x2) result(divisor)
    integer, intent(in) :: x1, x2
    integer :: divisor```

In this case fortpy fails to write a successful driver because it can't find a type to assign to gcd_2ints_fpy.
This issue may also be related to issue #37.

**Comment by rosenbrockc** [comment]
This was a parser issue in the executable parser. The syntax for functions with `result(variable)` describing the output were not supported. Revision 1.6.0 now supports this function syntax as well.

**Comment by wsmorgan** [comment]
Revision 1.6.0 changed how the makefile is setup but the issue remains. Here is a sample makefile that fortpy made for `function gcd_2ints(x1, x2) result(divisor)`. Notice that  code now tries to save the divisor result that was returned even though it is never assigned a value in the driver. The compiler throws this error:
```
gcd_2ints.f90:35.20:

    gcd_2ints_fpy = gcd_2ints(x1, x2)
                    1
Error: Function 'gcd_2ints' at (1) has no IMPLICIT type
gfortran: error: gcd_2ints.o: No such file or directory
```
The makefile looks like:
```
PROGRAM UNITTEST_gcd_2ints
  use rational_mathematics
  use fortpy
  implicit none

  integer :: x2
  integer :: x1
  integer :: divisor

  !Constant-input mode variables for xs
  integer :: fpy_file_xs, fpy_iostat_xs, fpy_repeat_xs = 0
  integer :: gcd_2ints_fpy
  real(fdp) :: fpy_start, fpy_end, fpy_elapsed = 0
  integer :: fpy_repeat

  !Auto-generated for xs; determine number of constants.
  open(fpy_newunit(fpy_file_xs), file='gcd_2ints.in')
  do
    read(fpy_file_xs, *, IOSTAT=fpy_iostat_xs)
    if (fpy_iostat_xs == 0) then
      fpy_repeat_xs = fpy_repeat_xs + 1
    else
      exit
    end if
  end do
  rewind(fpy_file_xs)
  
  do fpy_repeat = 1, fpy_repeat_xs
    read(fpy_file_xs, *) x1, x2

    call cpu_time(fpy_start)
    gcd_2ints_fpy = gcd_2ints(x1, x2)
    call cpu_time(fpy_end)
    fpy_elapsed = fpy_elapsed + fpy_end - fpy_start
    call pysave(divisor, 'gcd_2ints.out')
    !---------CLEANUP SEPARATOR---------------------------
  end do

  close(fpy_file_xs)
  call pysave(fpy_elapsed, 'fpytiming.out')
END PROGRAM UNITTEST_gcd_2ints
```

**Comment by rosenbrockc** [comment]
Thanks for the update. The reason `divisor` is showing up is that you have it declared explicitly using a `<global>` tag and you have assigned it as a `<target>`. You should change the name of the target to `[default]` for functions to save the actual function output. For example:

```xml
<target name="[default]" compareto="result.out" varfile="polya.out" when="each" />
```

As far as the compilation error goes, it appears that the explicit interface for the function is not visible to the program. There are two possibilities:

1. fortpy didn't add the `public` keyword in the driver it generated to make `gcd_2ints` publicly visible.
2. The function is part of an interface in the module; the interface is public. Since it belongs to the interface, fortran may not allow it to *also* be declared as a public function for the module.

Can you open the `rational_mathematics.f90` file in the unit test staging folder and verify whether it contains `public gcd_2ints` in the module declaration?

**Comment by wsmorgan** [comment]
`public gcd_2ints` is not in the rational_mathematics.f90 file, it just has `public gcd`.

**Comment by rosenbrockc** [comment]
This raises an additional question about how we ought to handle interfaces: should fortpy call the *interface* and let the compiler make sure it matches, or should it add the `public` keyword and test the subroutine directly?

Could you manually add the `gcd_2ints` to the public list and see if it compiles?

**Comment by wsmorgan** [comment]
With the gcd_2ints manually added to the public list it compiles just fine.

**Comment by rosenbrockc** [comment]
So, is it better to test the interface or the subroutine?

**Comment by wsmorgan** [comment]
In principle, as long as the tests cover all the different subroutines in
the interface, they should be equivalent. The question is can fortpy
recognize an interface?

Wiley Morgan
http://hagrid.byu.edu/Wiley#Bio

On Tue, Jun 16, 2015 at 3:26 PM, Conrad Rosenbrock <notifications@github.com

**Comment by wsmorgan** [comment]
To answer the question I posed earlier no it doesn't. Additionally the tests in numerical_utilities.f90 also call subroutines that are part of an interface except in those cases it makes the desired subroutine public. Why should gcd in rational_mathematics.f90 behave differently?

**Comment by rosenbrockc** [comment]
I agree, we should just test each module procedure in an interface separately. For the record, fortpy does support interface parsing. I will open a new issue related to the problem with the `public` keyword not being added since it doesn't have bearing on this original issue.
