### ISSUE TITLE
Parsing order for elements with pre-determined dimensions fails if intent statement after dimension declaration. 

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#50]
For example:
'integer, dimension(3), inent(INOUT) :: A'
Will produce the following code in the driver and won't compile:
'integer :: A(INOUT)'

**Comment by rosenbrockc** [comment]
Revision 1.6.0 addresses this error. False assumption in `variable.VariableParser._get_dim_modifier` that the last entry would be the dimensionality. That assumption is only true when the first `(` has its twin matched later in the parsing.
