### ISSUE TITLE
fpy_read does'n work for type character

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#52]
This is declared in the code:
    `character(500), intent(in) :: labeling `
The compiler produces this error:
```original_gIndx.f90:30.45:

  call fpy_read('labeling.in', '#', labeling)
                                             1
Error: There is no specific subroutine for the generic 'fpy_read' at (1)

**Comment by rosenbrockc** [comment]
Full support in Revision 1.6.0 up to 7d `character` arrays for `allocatable`, `pointer` and fixed dimension arrays.
