### ISSUE TITLE
Occassionally the subroutine being tested isn't made public for the test.

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#77]
When writing a test for a subroutine called get_list_at_this_size the following error popped up.
```
Undefined symbols for architecture x86_64:
  "_get_list_at_this_size", referenced from:
      _main in original.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```
I got the test to compile by going into the file and adding the line:
```
public get_list_at_this_size
```
and then in the auto-generated driver I added:
```
,only: get_list_at_this_size
```
after the use statement for the module. Only after both of these fixes would it compile.

**Comment by rosenbrockc** [comment]
Fixed in Revision 1.7.4.
