### ISSUE TITLE
Compiler Family Replacements in Model Outputs

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#88]
We have to use different compiler families with `[f]` because of random seed variations between versions. Currently I have the following in the XML file:

```xml
  	<output identifier="training_set_structures.dat" folder="../tests/uncle"
		file="training_set_structures.[f].dat.{}" template="integer.xml" />
```

The `file="training_set_structures.[f].dat.{}"` is not replacing `[f]` when looking for the model output, so the tests fail.

**Comment by rosenbrockc** [comment]
Fixed in Revision 1.7.5
