### ISSUE TITLE
Incomplete file transfer for some tests.

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#94]
This seems to happen randomly but at times the input files aren't completely copied from their original locations to the test directories. For example:
```
# Cluster number (total/of this kind):   324 /    191
   191
# Number of vertices:
   4
# Avg. Distance:
  0.809017
# Vertices: (x,y,z) | d-vector label | s-vector
     -2.000000       -1.000000        0.000000         1       3
     -1.000000       -1.000000        0.000000         1       1
     -1.000000        0.000000        0.000000         1       2
      0.000000        0.000000        0.000000         1       3
#
#--------------------------------------------------------------------------------
# Cluster number (total/of this kind):   325 /    192
   192
# Number of vertices:
   4
# Avg. Distance:
  0.809017
# Vertices: (x,y,z) | d-vector label | s-vector
     -2.000000       -1.000000        0.000000         1       3
     -1.000000       -1.000000        0.000000         1       1
     -1.000000        0.000000        0.000000         1       3
```
the last cluster in this file is missing its last vertex. Additionally the original input file has 886 clusters rather than just the 325 listed here. Somehow some of the file is getting lost. This error causes the test executable to produce this error:
```
At line 1260 of file io_utilities.f90 (unit = 10, file = 'clusters.out')
Fortran runtime error: End of file
```
However the python test script doesn't catch this as the end of the test so the test ends up hanging rather than producing an error and moving on.

**Comment by rosenbrockc** [comment]
In Revision 1.7.5 the default is now to symlink files instead of copying them. If this doesn't fix your issue, please let me know.
