### ISSUE TITLE
Comparison fails when model output file has capitol letters in it.

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#96]
Model output and actual output are saved in PI_matrix.out.* files. The code is trying to compare it pi_matrix.out which does not exist.
```
ERROR: can't create representation for /Users/wileymorgan/Documents/research/new_uncle/uncle/unittests/uncle.generateFigures.g49/tests/uncle_mode11.sc6/pi_matrix.out. File does not exist.
```

**Comment by rosenbrockc** [comment]
Can't reproduce the error. Please verify the file existence and update us.
